name: toastification
description: Toastification is a Flutter package that allows you to easily show toast and notification messages in your application.
version: 1.2.1
homepage: https://payamzahedi.com/toastification/
repository: https://github.com/payam-zahedi/toastification

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^4.1.0
  pausable_timer: ^3.1.0+3
  collection: ^1.16.0
  flutter_svg: ^2.0.10+1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
